### ISSUE TITLE
无法修改内存卡(SD卡)中的歌曲的信息

### ISSUE THREAD

**Issue by hosxy** [rRemix/APlayer#10]
对位于SD卡中的歌使用音乐标签编辑就会报错，也无法删除，但是手机内置储存就没问题
报错如图所示：
![default](https://user-images.githubusercontent.com/17108640/42488682-48f0c43c-8439-11e8-9ab6-feed940a2dd7.PNG)

**Comment by rRemix** [comment]
@hosxy 感谢反馈，我想办法找个带sd卡的手机测试下。
