### ISSUE TITLE
安卓P 无法识别歌曲

### ISSUE THREAD

**Issue by charlieshen7** [rRemix/APlayer#11]
系统是Nos 9.0，歌曲无法被正确识别，就是手机里面是有歌曲的，但是软件无法识别，也不能播放，不知道作者知不知道原因

同类的Retro Music也有同样的问题，但是网易云音乐可以正常识别

**Comment by charlieshen7** [comment]
手动扫描也没有用😂选择文件夹后提示扫描了X首歌曲，但是软件歌曲库里面依然没有显示

**Comment by rRemix** [comment]
@charlieshen7 看下歌曲目录下有没有.nomedia的隐藏文件

**Comment by charlieshen7** [comment]
没有诶，ES文件浏览器打开了显示隐藏文件，但是没有看见  sad

**Comment by rRemix** [comment]
@charlieshen7 歌曲是在sd卡吗？

**Comment by charlieshen7** [comment]
@rRemix 不诶，设备是一加3T，不知道是不是系统的bug，但是讲道理不应该啊没看见基安有人反映😂

**Comment by rRemix** [comment]
@charlieshen7 这个我也不太清楚了。。一般来说扫描不出来就是歌曲目录下有.nomedia的隐藏文件。

**Comment by charlieshen7** [comment]
@rRemix 终于搞定了，清楚手机中“媒体储存设备”这个软件相关的缓存数据重启后就可以正常识别手机内的歌曲了~
