### ISSUE TITLE
重大bug，在汽车的车机里使用可以读取但无法播放USB设备中的音乐

### ISSUE THREAD

**Issue by liyandong** [rRemix/APlayer#122]
重大bug，在汽车的车机里使用可以读取但无法播放USB设备中的音乐

**Comment by rRemix** [comment]
播放报的什么错

**Comment by liyandong** [comment]
提示“音乐文件不存在”
![微信图片_20210412011802](https://user-images.githubusercontent.com/961072/114314385-fb2f9d00-9b2c-11eb-9df6-4b9fe683b209.jpg)

**Comment by rRemix** [comment]
外置的存储因为谷歌的问题，目前确实有不少问题，不太好解决

**Comment by liyandong** [comment]
扫描的到文件，也读取的到封面，就是不能播放，吼吼

**Comment by rRemix** [comment]
已解决
