### ISSUE TITLE
设置中显示问题

### ISSUE THREAD

**Issue by shenzhiming88** [rRemix/APlayer#129]
您好！
如图所示，刚设置好“仅在WiFi下”之后是正常的，但是重新启动软件之后，该选项会显示“总是”，但是设置仍为“仅在WiFi下”
![SAVE_20210421_225706](https://user-images.githubusercontent.com/66902050/115575532-384a1b00-a2f5-11eb-8931-893dab338351.jpg)
请修复一下，谢谢

**Comment by rRemix** [comment]
下版本修复

**Comment by shenzhiming88** [comment]
已修复
https://github.com/rRemix/APlayer/releases/tag/v1.5.7.6.2
