### ISSUE TITLE
被oneplus下架了，说是有病毒

### ISSUE THREAD

**Issue by iminto** [rRemix/APlayer#137]
这个是什么原因导致的呀，能不能去跟一加反馈下

**Comment by rRemix** [comment]
问题是我没有上架过一加的应用市场

**Comment by iminto** [comment]
![aplayer](https://user-images.githubusercontent.com/284101/119121146-a6524100-ba5f-11eb-8709-db863c76b2ab.jpg)
显示这样，那可能被人恶意冒用了
