### ISSUE TITLE
能不能优化一下随机播放算法呀？

### ISSUE THREAD

**Issue by LiuDianshi** [rRemix/APlayer#14]
一直循环某几首歌，不知道能不能优化一下呀？谢谢！

**Comment by rRemix** [comment]
确定播放队列里面有很多歌曲吗？

**Comment by Gokou-Ruri** [comment]
@rRemix https://youtu.be/jpAefeUqt80
如果播放队列中新添加了歌曲，随机播放功能无法实时读取新歌曲，只能随机旧歌曲。
必须切换到顺序播放模式，且点击（或自动）“下一首”按钮以后，再切换回随机播放模式，才能随机队列中的所有歌曲。
可能楼主反馈的问题和我录像中是同一个情况，我在录像中为了突显“随机功能无法随机新添加的歌曲”，所以旧歌曲只选了一首。

**Comment by rRemix** [comment]
@Gokou-Ruri 我尽快修复这个问题。

**Comment by Gokou-Ruri** [comment]
谢谢！

**Comment by rRemix** [comment]
@Gokou-Ruri 新版本应该已经修复了。
