### ISSUE TITLE
清除缓存时应用崩溃

### ISSUE THREAD

**Issue by shenzhiming88** [rRemix/APlayer#140]
您好！
log下载地址：https://wwa.lanzoui.com/itrJoplnsyb
在08:35:55左右
应该和这一段有关
<details>
<summary>
详细信息
</summary>
<pre>
<code>
05-30 08:35:55.766  7418  7559 W DiskLruCacheWrapper: Unable to clear disk cache or disk cache cleared externally
05-30 08:35:55.766  7418  7559 W DiskLruCacheWrapper: java.io.IOException: not a readable directory: /data/user/0/remix.myplayer/cache/image_manager_disk_cache
05-30 08:35:55.766  7418  7559 W DiskLruCacheWrapper: 	at com.bumptech.glide.k.c.b(Util.java:7)
05-30 08:35:55.766  7418  7559 W DiskLruCacheWrapper: 	at com.bumptech.glide.k.a.i0(DiskLruCache.java:2)
05-30 08:35:55.766  7418  7559 W DiskLruCacheWrapper: 	at com.bumptech.glide.load.engine.y.e.clear(DiskLruCacheWrapper.java:1)
05-30 08:35:55.766  7418  7559 W DiskLruCacheWrapper: 	at com.bumptech.glide.load.engine.i.e(Engine.java:1)
05-30 08:35:55.766  7418  7559 W DiskLruCacheWrapper: 	at com.bumptech.glide.c.b(Glide.java:2)
05-30 08:35:55.766  7418  7559 W DiskLruCacheWrapper: 	at remix.myplayer.ui.activity.SettingActivity$c$a.run(SettingActivity.kt:4)
</code>
</pre>
</details>

**Comment by shenzhiming88** [comment]
@rRemix 
您好！
还有另外一个和缓存有关的问题，就不开issue了
就是这个缓存大小感觉不对劲，刚用十几分钟缓存就达到了60MB，之前的版本不会这样的，一个多月最多2MB

**Comment by shenzhiming88** [comment]
@rRemix 您好！
您那边可以测试一下有该问题吗？我这边用好几台设备测试都有该问题

**Comment by rRemix** [comment]
@shenzhiming88 有个手机上能复现，下个版本修复

**Comment by shenzhiming88** [comment]
已解决，感谢
