### ISSUE TITLE
[Bug]保存歌曲搜索顺序失败

### ISSUE THREAD

**Issue by shenzhiming88** [rRemix/APlayer#142]
您好！
可能和 https://github.com/rRemix/APlayer/issues/140 是同一个问题
![Screenshot_2021-05-31-23-36-55-890_remix myplayer](https://user-images.githubusercontent.com/66902050/120216197-4763a780-c269-11eb-9526-338036bce449.jpg)

**Comment by rRemix** [comment]
应该是同一个问题，不知道为啥在你手机上应用内部的数据都保存失败了

**Comment by shenzhiming88** [comment]
已解决
