### ISSUE TITLE
无法手动选择匹配歌词

### ISSUE THREAD

**Issue by shadowdragon1123** [rRemix/APlayer#149]
上一版本1.5.7.7可以选择 但是会崩溃
最新的1.5.7.8点击手动选择 显示功能不可用

**Comment by rRemix** [comment]
高版本手动选择可能是有兼容性的问题，目前没太好的办法解决

**Comment by shadowdragon1123** [comment]
> 高版本手动选择可能是有兼容性的问题，目前没太好的办法解决

是指安卓系统版本还是软件版本？
我是安卓10

**Comment by Henry-ZHR** [comment]
> 
> 
> > 高版本手动选择可能是有兼容性的问题，目前没太好的办法解决
> 
> 是指安卓系统版本还是软件版本？
> 我是安卓10

Android 10+ 或 APlayer 15770+
