### ISSUE TITLE
请问通知栏取色是如何做到的

### ISSUE THREAD

**Issue by Anzhi-Meiying** [rRemix/APlayer#15]
我使用了系统通知api也没有自动取色，Android O

**Comment by rRemix** [comment]
不是取色吧，只是设置深色或者浅色模式。相应的代码网上很多。

**Comment by Anzhi-Meiying** [comment]
@rRemix 就是这个
![image](https://user-images.githubusercontent.com/13428030/50475836-eb91f600-0a00-11e9-963e-43c4a225bf86.png)
这是怎么做到的

**Comment by rRemix** [comment]
不好意思，我看成状态栏了。。那个地方就是官方提供的api
具体参考 [NotifyImpl24.kt](https://github.com/rRemix/APlayer/blob/master/app/src/main/java/remix/myplayer/service/notification/NotifyImpl24.kt)

**Comment by rRemix** [comment]
这个你只能自己检查下代码了。。
