### ISSUE TITLE
能否添加对远程文件夹(webdav,samba)的支持

### ISSUE THREAD

**Issue by zhaoxp520** [rRemix/APlayer#156]
能否添加对远程文件夹的支持
歌曲比较多比较大，放到手机里面不太现实
想说能否放在远程服务器，通过webdav这类协议进行连接后，播放远程文件夹的歌曲
通过mix,es之类的挂载的webdav却无法全部调用播放器播放
所以想说看看能不能播放器的媒体库直接支持webdav
就像一个APP叫我的听书一样

**Comment by Henry-ZHR** [comment]
只能说有难度

目前所有东西基于 Android 的 MediaStore，MediaStore 读不到的都不行

不过如果你说的“挂载“是我理解的那样，可能可以试试用什么办法让 MediaStore 读到？

**Comment by rRemix** [comment]
已支持， 可以等下新版
