### ISSUE TITLE
播放界面、功能建议。

### ISSUE THREAD

**Issue by Gokou-Ruri** [rRemix/APlayer#16]
请问播放界面的UI和操作逻辑可否参考一下phonograph（点唱机）这款程序？也是一款开源播放器。
封面和状态栏无缝融合（状态栏透明），左/右滑封面切换上/下一首歌曲。
而歌词界面和分享界面可以用上/下滑动的操作逻辑，不需要切换整个界面，上/下滑动切换时只改变封面区域就行了。这样既可以达到酷炫的视觉效果，操作上也很方便。
![screenshot_aplayer_20190211-143727](https://user-images.githubusercontent.com/26711804/52548832-d7685380-2e0a-11e9-9b58-fe0de7699f0c.png)

歌词界面有个小问题：如果当前是歌词查看模式，然后将程序后台，再回到程序，会变回封面模式，需要再次切换回歌词模式，而且封面图还会短暂出现空白现象。
![2019_02_11_03_06_16](https://user-images.githubusercontent.com/26711804/52548876-19919500-2e0b-11e9-88bc-602cb04ff973.gif)

功能建议：希望能支持*.cue播放列表，这样就能直接播放整轨音频了。

程序“关于”界面下显示异常：
系统：aosp extended 5.6（Android 8.1）
屏幕：1440x2560（dp 600/dpi 384/xhdpi）
dp≥600就是平板模式了。
![screenshot_aplayer_20190211-145113](https://user-images.githubusercontent.com/26711804/52549122-85c0c880-2e0c-11e9-9fb2-a6f03de77d19.png)

**Comment by rRemix** [comment]
1.参考点唱机这个改动太大了，不考虑了
2.这个问题后续版本我会修复
3.cue这个貌似没法支持，歌曲列表读取的是系统数据库
4.这个问题我也会去看看。
