### ISSUE TITLE
应用被Google Play下架？

### ISSUE THREAD

**Issue by qjzcj2008** [rRemix/APlayer#161]
今天突然发现应用的GP页面不见了，如下图提示，是因为什么原因被下架了吗🤔还可以恢复吗？
![image](https://user-images.githubusercontent.com/16514953/147562225-d155e86f-be29-4f23-b345-b13f066c0f84.png)

**Comment by rRemix** [comment]
正在排除

**Comment by qjzcj2008** [comment]
我这边看已经恢复上架状态了，商店页已经可以访问了。
顺便问一句最近有发新版的打算吗（小声😂

**Comment by rRemix** [comment]
年前我会发一版的，把大家最近的更新都上了

**Comment by qjzcj2008** [comment]
好的，了解了，谢谢😊
既然已经恢复上架了，我就close了
