### ISSUE TITLE
【功能建议】添加歌词下载功能

### ISSUE THREAD

**Issue by ericclose** [rRemix/APlayer#169]
请问下能否添加歌词下载的功能以供完全离线使用。

**Comment by rRemix** [comment]
在Android/data/remix.myplayer/lyric下

**Comment by qindeng** [comment]
> 在Android/data/remix.myplayer/lyric下

能改到跟歌曲同一目录下面吗?还有就是做一个在歌曲同目录有歌词的就显示吗?

**Comment by cancundeyingzi** [comment]
> > 在Android/data/remix.myplayer/lyric下
> 
> 能改到跟歌曲同一目录下面吗?还有就是做一个在歌曲同目录有歌词的就显示吗?
后者是有这个功能的，前者的话，应该是为了规范开发吧。

**Comment by qindeng** [comment]
Dear,       我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
