### ISSUE TITLE
排序问题

### ISSUE THREAD

**Issue by asepsiswu** [rRemix/APlayer#17]
标题排序，基本无序。
![Screenshot_2019-03-14-20-40-19-613_remix myplayer](https://user-images.githubusercontent.com/4438057/54364361-b6b04980-46a7-11e9-809e-d9b34886f965.png)

**Comment by rRemix** [comment]
系统数据库就是这样排的。。

**Comment by asepsisWu** [comment]
可以添加这项功能，进行重新排序吗

**Comment by rRemix** [comment]
目前的话就只能把歌曲添加到播放列表里面，然后进入播放列表里面选择手动排序。
