### ISSUE TITLE
[歌词] 请求适配 墨•状态栏歌词

### ISSUE THREAD

**Issue by xiaowine** [rRemix/APlayer#176]
在版本更新前，我通过Hook可以获取歌词，但版本更新后，classloader点更改，导致无法使用
虽然我可以再次适配，但希望可以您适配我们，使用我们的api，减少我的工作量
使用我模块的用户中，有不少是Aplayer用户，您的适配可以说是双赢
望适配
[Api项目地址](https://github.com/Block-Network/StatusBarApiExample)(https://github.com/Block-Network/StatusBarApiExample)

**Comment by rRemix** [comment]
下个版本适配

**Comment by xiaowine** [comment]
> 下个版本适配

感谢，希望你尽快发版
