### ISSUE TITLE
请问“当前播放队列”功能在哪里查看？

### ISSUE THREAD

**Issue by Gokou-Ruri** [rRemix/APlayer#18]
到处都没找到“播放队列”。
需求：对新添加的歌曲会喜欢循环播放几天（欣赏+学唱），这类短期循环播放的歌曲并不适合添加为固定的播放列表（因为歌曲风格往往截然不同），所以以前使用其它播放器时都会手动添加新歌到“播放队列”，不添加旧歌曲。但是在aplayer上我没找到这个队列在哪里查看，请开发者告知一下，感谢！
![Screenshot_20190323-205220_APlayer](https://user-images.githubusercontent.com/26711804/54866347-a1c16d80-4dad-11e9-9825-38403b62cecc.png)

![Screenshot_20190323-204033_APlayer](https://user-images.githubusercontent.com/26711804/54866336-6757d080-4dad-11e9-8b30-f0b47e40d7a1.png)

**Comment by rRemix** [comment]
播放界面有个按钮，可以查看播放队列。

**Comment by Gokou-Ruri** [comment]
@rRemix 我……我怎么这么蠢……
感谢开发者提醒！（我都不知道为啥会把这个眼皮底下的按钮给忽略掉了……
