### ISSUE TITLE
您好，希望可以支持一下自建歌单

### ISSUE THREAD

**Issue by linsmod** [rRemix/APlayer#181]

**Comment by kissstudio** [comment]
可能期望类似网抑云音乐那种...可以吗

**Comment by Henry-ZHR** [comment]
不是很懂 现有的歌单功能还缺少什么？

**Comment by kissstudio** [comment]
不好意思，之前没注意，后来已经看到有歌单功能。

然后后来的后来，其实是想要表达，希望有一个，类似网抑云音乐那种，一个红心❤按钮，把当前播放的添加到“我喜欢的”类别的快捷方式。

**Comment by Henry-ZHR** [comment]
播放页和列表的三点菜单都有“收藏”  会直接加到歌单“我的收藏”里

**Comment by rRemix** [comment]
直接放播放界面主要不知道放哪。。
