### ISSUE TITLE
找不到曾经用过的功能，很需要😭😭

### ISSUE THREAD

**Issue by P095877** [rRemix/APlayer#189]
上一部手机安装了这个app，但是手机打不开了，试着重新下载后发现很多功能没有了。
之前使用的版本里有一个专门的播放列表栏，可以很快捷地分类不同批次的音乐列表，例如“最新加入”、“全部歌曲”、“收藏”、“我的歌单1”...只要有点开一个单独的歌单就会生成一个全新的播放列表，在播放列表可以随意删改音乐而不会影响到歌单内容，而且播放到哪首歌都是有记忆的，不会重新点开就重新从第一首开始播。这个播放列表的功能真的很方便TAT
之前的版本还有显示播放次数，也默认有“播放最多”或是“从未播放”的列表。
还可以把默认显示的“专辑”、“歌手”栏关掉。
备份音乐列表也是点一下就会生成备份文件，接着选择是否覆盖之前的备份...
在网上翻了个底朝天也没找到旧手机里的那个😭😭😭这是为什么呢，是更新之后删减了还是其实不是同一个app😭😭😭找了一晚上也没找到心里真的很难受😭😭😭😭😭我要怎么才能找到它呢😭
希望有人可以帮帮我😢

**Comment by P095877** [comment]
对了而且歌单列表是不显示封面图片的，这也是那个版本对我来说唯一不足的地方。

**Comment by P095877** [comment]
除了这些几乎一切都是一样的，到底为什么找不到😭

**Comment by rRemix** [comment]
应该不是这个app，没有做过"从未播放"功能，应该是其他开发者fork过去二次开发的
