### ISSUE TITLE
我很乐意为您的项目创建内容

### ISSUE THREAD

**Issue by HarryHeights** [rRemix/APlayer#19]
嗨，我今天检查了你的项目。这太棒了。我期待一个基本的音乐播放器，但当我看到该应用程序的高级功能时，我感到很惊讶。我很乐意通过创建某些文档为您的项目做出贡献。隐私政策，常见问题解答，贡献者指南等。我很想知道您对此的看法。

Hi, I checked out your project today. It's really amazing. I was expecting a basic music player, but I was surprised when I saw the app's advanced features. I'd love to contribute to your project by creating certain documents. A privacy policy, FAQs, contributors guide etc. I'd love to know what you think about that.

**Comment by rRemix** [comment]
@HarryHeights i'm looking forward to any of your contribution!

**Comment by HarryHeights** [comment]
Good day @rRemix . Didn't know you speak English. Well, translating the content of the readme to English isn't a problem. I could that. It'll be nice to have the readme in Chinese and another for English. If it'd help, the contents I'll be creating, I'll make separate copies one in English and the other in Chinese.

**Comment by rRemix** [comment]
thanks, i really hope for you pr

**Comment by HarryHeights** [comment]
I'll send the PRs really soon. By the way, for the privacy policy, I'd love to know how you deal with user information. Do you have any access to user information when they utilize the app? I will also like to know the third-party libraries the app uses.

**Comment by rRemix** [comment]
I don't access any user information by myself, but bugly, which is tencent's crash report library, may do it. All third-party libraries i used is described in READ.md. I just updated it.
