### ISSUE TITLE
应用通知

### ISSUE THREAD

**Issue by Edfgdz** [rRemix/APlayer#2]
应用设置里面把经典通知栏样式关了以后，重启应用后，发现通知栏播放器还是经典样式

**Comment by rRemix** [comment]
@Edfgdz 手机型号？操作系统？我的手机上这个问题并没有复现。

**Comment by Edfgdz** [comment]
型号华为honor8 FRD-AL00,系统emui4.1

**Comment by Edfgdz** [comment]
用邮箱回复过去了

**Comment by Edfgdz** [comment]
通知设置在哪儿?

![screenshot_2018-02-01-21-46-53](https://user-images.githubusercontent.com/26460124/35777667-ec315336-09ec-11e8-92d7-0e853a302f70.jpg)

**Comment by Edfgdz** [comment]
可以修复吗？

**Comment by rRemix** [comment]
@Edfgdz 应该早就修复了呀。。你那还是不正常？

**Comment by Edfgdz** [comment]
通知栏样式的设置选项没找到在哪儿

**Comment by Edfgdz** [comment]
是特例还是咋回事?
