### ISSUE TITLE
最新版丢失桌面歌词按键

### ISSUE THREAD

**Issue by cornahere** [rRemix/APlayer#201]
更新至 v1.6 并使用原生通知栏样式时，原有的桌面歌词按钮消失。

测试系统为 PixelExperience 13 与 MIUI 14。

![Screenshot_20230618-134941_APlayer_015015.png](https://github.com/rRemix/APlayer/assets/79489425/bf17f66d-aef9-462a-80c6-5c7da3357487)

![Screenshot_2023-06-18-13-52-36-704_remix.myplayer.jpg](https://github.com/rRemix/APlayer/assets/79489425/d1db4e2e-3ad4-4c13-92de-db7ad4ac152a)

**Comment by rRemix** [comment]
能复现的话下版本修复
