### ISSUE TITLE
能不能加入WebDav等网络歌曲播放功能？

### ISSUE THREAD

**Issue by xxynet** [rRemix/APlayer#204]
能不能加入WebDav等网络歌曲播放功能？

**Comment by Mickeywaugh** [comment]
对于家里有NAS的人来说，如果能支持WebDAV那就太好了。这样不需要同一份音乐，在几个设备上都要保存一份。

**Comment by YUNDAN21** [comment]
同求

**Comment by rRemix** [comment]
最新代码以支持，可以先跑跑看看 @xxynet @Mickeywaugh @YUNDAN21

**Comment by xxynet** [comment]
> 最新代码以支持，可以先跑跑看看 @xxynet @Mickeywaugh @YUNDAN21 

感谢大佬！！！
就是有一个bug，我想用这个听alist存的歌，alist的webdav路径是在ip+端口后面还要加“/dav”，APlayer无法读取

![Screenshot_2024-03-23-18-22-52-249_remix.myplayer.jpg](https://github.com/rRemix/APlayer/assets/60773145/cc81ac91-8541-4605-8fbe-fe4f74e6fe67)

**Comment by aqxgm1979** [comment]
通过webdav可以成功连接到群晖的主目录，但是打不开下面的子目录

**Comment by xxynet** [comment]
> 通过webdav可以成功连接到群晖的主目录，但是打不开下面的子目录

我也是，只能等作者解决了

**Comment by rRemix** [comment]
@xxynet 能否给个测试的环境，可以的话发送到568920427@qq.com

**Comment by rRemix** [comment]
@aqxgm1979 @xxynet 可以试试这个版本是否修复 
[APlayer-v1.6.4.0-nonGoogle-withUpdater-release.zip](https://github.com/user-attachments/files/16319538/APlayer-v1.6.4.0-nonGoogle-withUpdater-release.zip)

**Comment by xxynet** [comment]
> @aqxgm1979 @xxynet 可以试试这个版本是否修复 
> [APlayer-v1.6.4.0-nonGoogle-withUpdater-release.zip](https://github.com/user-attachments/files/16322647/APlayer-v1.6.4.0-nonGoogle-withUpdater-release.zip)
> 

这个版本可以正常使用了！感谢！

**Comment by aqxgm1979** [comment]
收到，感谢大佬！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月24日 16:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [rRemix/APlayer] 能不能加入WebDav等网络歌曲播放功能？ (Issue #204) |

@***@***.*** 可以试试这个版本是否修复
APlayer-v1.6.4.0-nonGoogle-withUpdater-release.zip

这个版本可以正常使用了！感谢！
