### ISSUE TITLE
切换应用会自动由歌词界面转到封面页

### ISSUE THREAD

**Issue by wurarara** [rRemix/APlayer#207]
先调到歌词页面，然后进入任务视图，就是导航栏按那个小方块进去的那个多任务视图，再返回软件时会自动从歌词界面切换走....有点小麻烦，每次都要重新划回来(⁠ ⁠；⁠∀⁠；⁠)
顺带一提，如果直接返回桌面，点击软件，这个时候会从播放页面直接跳到你之前选择的首页的那个列表，比如“歌曲“、”专辑“、“文件夹”，不过这个倒是无伤大雅...

**Comment by rRemix** [comment]
问题1我并没有复现，是切换到首页吗？
问题2我倒是复现了，下版本修复

**Comment by wurarara** [comment]
> 问题1我并没有复现，是切换到首页吗？ 问题2我倒是复现了，下版本修复

@rRemix 是我说的复杂了，就是调到歌词页面，然后切换到其他应用，再回来，这时候就不在歌词页面了，比如外语歌，每次听到高兴的时候想看看歌词，然后一返回歌词没了(⁠╥⁠﹏⁠╥⁠)

**Comment by rRemix** [comment]
最新代码已修复
