### ISSUE TITLE
Some lyrics special characters not displayed correctly

### ISSUE THREAD

**Issue by ThreeDeeJay** [rRemix/APlayer#208]
Example, apostrophes (`'`) are dispalayed as `&apos;`
![image](https://github.com/rRemix/APlayer/assets/71472458/4fe3552a-0670-45f4-bb11-f7b709879c33)
Seems like an English character set issue 🤔

**Comment by Henry-ZHR** [comment]
Which lyric source are you using?

You can check it by selecting each item in "lyric" of three dots menu.

**Comment by ThreeDeeJay** [comment]
@Henry-ZHR @rRemix Nice! 
Is the update pre-release APK available to download anywhere? 👀
