### ISSUE TITLE
歌曲库能够增加 专辑艺术家、流派分类显示。

### ISSUE THREAD

**Issue by wcylj** [rRemix/APlayer#211]
能不能增加风格/流派、专辑艺术家分类显示。
本地收集的歌曲，很多歌手、专辑只有一两首，数量巨大，寻找不方便。
通过自己编辑流派、专辑艺术家，可以把一些主要的提取出来。

进一步：如果能增加作词家、作曲家那就更好了。

**Comment by rRemix** [comment]
后续考虑增加一个流派

**Comment by Mickeywaugh** [comment]
大部分人听歌都不会去在意这个流派。至少我从来没有去关心过。
使用本地播放器的人，大部分都是自己收藏的音乐，稍微讲究点的，下载的是flac等高码率的音频文件。
我的习惯就是下载一堆音乐放到某个store下，然后从store里挑出一些变成favorite在某一段时间内重复听，然后找到新的喜欢的再加入到favorite里。
