### ISSUE TITLE
希望增加新功能：记录歌曲听的次数

### ISSUE THREAD

**Issue by tarkuvsky** [rRemix/APlayer#216]
十分感谢各位开发者的辛勤付出
这是我目前找到的最好的本地音乐播放器。
我特别喜欢用这个本地播放器，但还有一点不足，要是能记录这个听歌的次数就好了。
这样子能使我的听歌数据可视化，能让我看一看，我最近一段时间最近一年时间喜欢听什么歌，希望你们能够采纳，谢谢！

**Comment by Mickeywaugh** [comment]
不错的主意。

**Comment by rRemix** [comment]
@Zhouseeie Z 侧滑菜单有最近播放

**Comment by Zhouseeie** [comment]
你好，谢谢您的回复，我指的是像听歌排行这样的功能，十分感谢！

**Comment by tarkuvsky** [comment]
？

发自“Zhouseeie”的 iPhone4

**Comment by rRemix** [comment]
@tarkuvsky 最新版侧滑菜单中已经添加

**Comment by Henry-ZHR** [comment]
@rRemix 但是没显示具体次数？

**Comment by tarkuvsky** [comment]
对具体次数加排行

发自“Zhouseeie”的 iPhone4

**Comment by rRemix** [comment]
@tarkuvsky 最新代码已经添加，播放次数暂定显示在封面左边

**Comment by tarkuvsky** [comment]
谢谢！

发自“Zhouseeie”的 iPhone4

**Comment by tarkuvsky** [comment]
其实再提一个建议，本播放器专辑图片貌似不能加载（高质量的mp3格式中1-2m的专辑图片）（显示空白）

**Comment by rRemix** [comment]
@tarkuvsky 这个估计是系统问题了，可以试试打开设置中**忽略系统缓存中的媒体封面**这个选项
