### ISSUE TITLE
学习今日头条，在播放时候可以长按画面，以三倍速快进

### ISSUE THREAD

**Issue by lforlgg** [rRemix/APlayer#218]
建议：
1.长按封面可以2~3倍速快进
2.→滑动屏幕可以让进度条快进一小段
3.←滑动屏幕可以让进度条快退一小段

缘起：今日头条app中，在播放时候可以长按画面，以三倍速快进--这个功能非常方便。我们APlayer可以把这个吸纳进来。
目前外面的播放器，暂时还没有看到有这么便利的微调进度条的功能。

好处：
在音频比较长的时候（比如一个小时的评书或者有声读书节目），进度条限于屏幕宽度按比例定位不容易准确，可以大致调进度条到一定位置后，用快进辅助微调到自己想要听的比较准确的位置上。

感谢！
![long](https://github.com/rRemix/APlayer/assets/105794681/929447b9-26fc-4bef-ae04-64da79c0fbb5)

**Comment by rRemix** [comment]
下个版本加上

**Comment by rRemix** [comment]
已支持
