### ISSUE TITLE
歌词锁定后无法解锁

### ISSUE THREAD

**Issue by gj100705** [rRemix/APlayer#222]
Android13
Software Version：v1.6.1.0
启用桌面歌词如果点击锁定歌词，歌词可以成功锁定，但无法解锁，将永远在锁定时候的位置显示，重新开关桌面歌词也一样，只有在系统里清除应用数据重置设置才能重新解锁歌词

**希望在设置中加上解锁桌面歌词的按钮**

**Comment by CornaHere** [comment]
这个问题和#201是同一个问题。
如果退回1.6.0.2或更早的版本，会发现通知栏处有解锁按钮。
如果实在有需要，可以暂时退回旧版本，等待通知栏修复。

**Comment by rRemix** [comment]
估计是兼容性方面的问题，这几天我排查下

**Comment by gj100705** [comment]
> Owner

感谢更新，我这边发现在某次安卓系统安全更新后，通知栏可以看到歌词按钮和解锁按钮了，我想应该是安卓自身的问题。当前Android安全更新为2023/12/05，希望能有所帮助
