### ISSUE TITLE
[bug] 歌曲metadata读取失败

### ISSUE THREAD

**Issue by PYUDNG** [rRemix/APlayer#226]
## 前置信息
- 机型：华为nova8+, BRQ-AL00
- 系统：HarmonyOS 2.0.0 版本号2.0.0.168
- [x] 已经搜索过issues没有已知存在的重复issue

## 问题
歌曲metadata读取失败，表现为无法显示内嵌的封面和歌词、“歌曲详情”弹出错误提示并部分信息始终显示“正在加载”
很多歌曲都有这个问题，如图：
![Screenshot_20240305_225744](https://github.com/rRemix/APlayer/assets/63054558/e65a4235-0d94-45f2-8e52-f4739a7b1b56)

但并不是所有歌曲都这样，比如华为自带的《Dream it Possible》：
![Screenshot_20240305_224326](https://github.com/rRemix/APlayer/assets/63054558/be9c53f4-18f5-4cac-a48b-ad55c5ad486c)

出现此问题的歌曲同时包括flac和mp3两种格式的文件，其他格式未测试。
歌曲播放不受影响。

## 尝试过的解决方案
已经尝试过：
- 将歌曲文件改名并移动，使得整个歌曲路径中没有非ascii字符，且没有空格
  ![Screenshot_20240305_224127](https://github.com/rRemix/APlayer/assets/63054558/59d94c40-f1ee-4437-ada5-e5e74efb9603)
- 在系统设置-应用管理中撤销并重新授予存储权限
- 在黑名单中添加歌曲所在文件夹的祖先文件夹，以期授予文件夹访问权限

均无效果

## 歌曲文件样本
因华为自带的《Dream it Possible》文件管理器无权访问，故在此只能提供无法解析的歌曲文件
[歌曲样本.zip](https://github.com/rRemix/APlayer/files/14497244/default.zip)

## 日志
[logs.zip](https://github.com/rRemix/APlayer/files/14497268/logs.zip)

**Comment by rRemix** [comment]
我在多个版本的虚拟机上试了下都是可以正常读取的，如红色箭头所示。我怀疑是路径问题，我看截图都是非公共目录，可以试试把歌曲移动到Music这种公共目录下，如黄色箭头
![微信图片_20240306100819](https://github.com/rRemix/APlayer/assets/16172563/ca7dade1-1d66-4101-b7ab-90bb279ae9dc)

**Comment by Henry-ZHR** [comment]
看了一下应该是Android 11，如果设置有“管理所有文件”权限的话也可以试一下

**Comment by PYUDNG** [comment]
感谢回复，但…放到公共目录也没有效果
![Screenshot_20240306_195714_remix myplayer](https://github.com/rRemix/APlayer/assets/63054558/0c67cae8-1e85-490b-a81d-5b2f7c4adb6a)

**Comment by PYUDNG** [comment]
> 看了一下应该是Android 11，如果系统的设置里有“管理所有文件”权限的话也可以试一下

没有看到有这样的设置，系统版本查出来是这个…安卓10？
![截屏2024-03-07 上午8 17 11](https://github.com/rRemix/APlayer/assets/63054558/87ce6116-13d4-4b49-a0e0-60ac8967f9d7)

**Comment by Henry-ZHR** [comment]
Android 10大概是需要`requestLegacyExternalStorage`了

https://github.com/rRemix/APlayer/commit/7d431fce65803fac43800278e5da076e3a063e72#diff-7fa6aef292187a049f7a4d6060d8df3ba212d838789c78940bd363344b1c38cdL31

**Comment by PYUDNG** [comment]
感谢，是否有CI版本可以测试？

**Comment by Henry-ZHR** [comment]
这是删掉那个的commit，现在还没加回来。。。

**Comment by PYUDNG** [comment]
😂

**Comment by PYUDNG** [comment]
请问，这个现在还有在考虑修复吗？

**Comment by Henry-ZHR** [comment]
[APlayer_v1.6.2.0_nongoogle_2024-03-17 08-49.zip](https://github.com/rRemix/APlayer/files/14625722/APlayer_v1.6.2.0_nongoogle_2024-03-17.08-49.zip)

加上了requestLegacyExternalStorage

试试 行的话我开pr直接加上了

**Comment by PYUDNG** [comment]
感谢开发。

> [APlayer_v1.6.2.0_nongoogle_2024-03-17 21-55.zip](https://github.com/rRemix/APlayer/files/14627599/APlayer_v1.6.2.0_nongoogle_2024-03-17.21-55.zip)
> 
> 连着别的修改（#229）一起了 可以顺便试试还有什么别的问题

已测，音乐标签可以读了，其他使用上还没有发现有什么问题，但是内嵌封面只有少数歌曲可以显示，如图：
图一是Aplayer截图，只有部分歌曲内嵌封面有显示
<details><summary>长图，点击展开查看</summary>
<img title="图一" src="https://github.com/rRemix/APlayer/assets/63054558/c53c30c5-5398-45ef-b694-89d330c13141">
</details>
图二是[MaterialFiles](https://github.com/zhanghai/MaterialFiles)的截图，可以看到这些歌曲文件都是有内嵌封面的
<details><summary>长图，点击展开查看</summary>
<img title="图二" src="https://github.com/rRemix/APlayer/assets/63054558/76dfee79-0c16-4efd-8aca-fd426d48164a">
</details>

歌曲文件：受影响的歌曲文件太多了，如有需要我会提供样本
日志：[logs.zip](https://github.com/rRemix/APlayer/files/14628402/logs.zip)
其他信息：设置里的联网获取封面已经关闭并且清除了已下载封面

**Comment by PYUDNG** [comment]
后台播放了一段时间发现歌曲封面加载出来了，可能只是加载大量歌曲比较慢吧

**Comment by PYUDNG** [comment]
目前新版本我用着也没什么问题，感谢开发，同时期待release

**Comment by Henry-ZHR** [comment]
混淆了之后好像好点？你试试

[APlayer_v1.6.2.0_nongoogle_2024-03-21 13-02.zip](https://github.com/rRemix/APlayer/files/14684694/APlayer_v1.6.2.0_nongoogle_2024-03-21.13-02.zip)

照例试试有没有什么别的问题

**Comment by Henry-ZHR** [comment]
> 感谢开发，同时期待release

等那个pr被merge了之后 我再开pr再改

~~你先别急 让我先急~~

**Comment by PYUDNG** [comment]
> 等那个pr被merge了之后 我再开pr再改

好，那咱就暂且偷点懒
