### ISSUE TITLE
列表异常

### ISSUE THREAD

**Issue by wcy6419** [rRemix/APlayer#230]
《从已有播放列表导入》导入歌单后，切换到列表，闪退。
清空程序数据后，从外部存储逐个导入，正常了。

**Comment by rRemix** [comment]
按操作方法没复现到。。。

**Comment by wcy6419** [comment]
之前出现过，具体原因未知，清空数据好了。
今天又复现了：
1、导入多个列表。
2、更改列表排序方式，重复了几次，最后是名称排序。
3、切换到其他媒体库，再切换回来闪退。
4、重新打开，只要点击列表就闪退。

**Comment by rRemix** [comment]
好的，我尝试复现下

**Comment by rRemix** [comment]
@wcy6419 已修复
