### ISSUE TITLE
Alist的WEBDAV下的flac无法播放

### ISSUE THREAD

**Issue by Mickeywaugh** [rRemix/APlayer#232]
如题。
播放WEB DAV的flac会导致程序无响应。
看好像有mediaplayer... what =-38,extra 0 的错误钷。
然后提示java.lang.illegalstate.exception

**Comment by rRemix** [comment]
试试本地的flac能播放吗

**Comment by Mickeywaugh** [comment]
本地flac能播放。

**Comment by Mickeywaugh** [comment]
需要测试环境么？

**Comment by rRemix** [comment]
我先尝试复现下

**Comment by rRemix** [comment]
> 需要测试环境么？

需要测试环境 @Mickeywaugh

**Comment by Mickeywaugh** [comment]
若需要测试服务器的话可以Email我。Mickeywaugh@qq.com

**Comment by www766** [comment]
> 需要测试环境么？

大佬其他已久的webdav终于有了，可是如题确实不能用。

能够接连上群晖NAS，但是俩问题：
1、nas下存放根目录的音乐可以访问、但是根目录下面的二级目录不显示；
2、能访问只是能看到文件信息，但是音乐文件都播放不了，提示java什么的错误信息，不局限于flac、mp3也播放不了。

**Comment by Wingsofbighuang** [comment]
楼主解决了吗？我也遇到相同的问题，aplayer挂载远程webdev，能看到文件，但是无法播放。文件格式flac

**Comment by rRemix** [comment]
@Wingsofbighuang 最近在带娃，我尽量抽空解决下

**Comment by blacktea1891** [comment]
不知道问题解决没，aplayer挂载alist的webdav，二级文件夹能看到，但是无法打开。显示“请稍等”后就没了。根目录下能看到文件但是打不开，不光是flac，mp3，m4a也无法打开

**Comment by rRemix** [comment]
@blacktea1891 flac已经修复了，最好能提供下你的测试环境，我再多测试下
