### ISSUE TITLE
操作逻辑优化建议

### ISSUE THREAD

**Issue by wurarara** [rRemix/APlayer#234]
复现：播放歌曲并进入播放页面，滑动到歌词页面，点击home回到桌面，进入手机任务视图，选择aplayer，会自动从歌词页面转到专辑封面页。
-----个人感觉逻辑上比较奇怪，一般应该是回到之前应用的状态，而且歌词页面相对常用。
ps：上次您说要修复来着，被骗了(⁠´⁠；⁠ω⁠；⁠｀⁠)

**Comment by rRemix** [comment]
好的，我看下这个问题
