### ISSUE TITLE
播放历史&最近添加不显示歌曲

### ISSUE THREAD

**Issue by wurarara** [rRemix/APlayer#237]
设备：手机
系统：Android 6
版本：1.6.2.0（之前的版本没太注意过，印象中一直没有）
使用同品牌Android 8手机测试后未发现以上问题。
不清楚是不是个例（存储权限已给），而且系统版本比较低了，用的人少，似乎没有修复的必要。
简单提一嘴⁠(⁠‾⁠.⁠‾⁠“⁠)⁠

**Comment by rRemix** [comment]
只能用模拟器试试了
