### ISSUE TITLE
关于通知栏播放控件的两个问题。

### ISSUE THREAD

**Issue by Gokou-Ruri** [rRemix/APlayer#24]
如果将通知样式设置为“经典”，底色选“使用系统底色”，就会导致通知栏的歌曲名字体颜色和通知栏背景色融合，看不见歌曲名。
（虽然不开启“经典”通知样式就不会出现此问题，但因为Android通知栏默认白色背景，如果使用新通知样式，aplayer通知底色随歌曲封面变色，会导致aplayer的通知配色和其它所有通知（白色）不协调，视觉上有些突兀。
系统：Android 9 （aex6.4）
aplayer：1.5.2.1
![Screenshot_20190425-192827_Chrome](https://user-images.githubusercontent.com/26711804/56732552-5e816280-6790-11e9-8e8e-4d472bb4be50.png)
![Screenshot_20190425-192838_Chrome](https://user-images.githubusercontent.com/26711804/56732553-5f19f900-6790-11e9-96e1-83f4af98e6ad.png)
![Screenshot_20190425-192913_APlayer](https://user-images.githubusercontent.com/26711804/56732609-87095c80-6790-11e9-946e-d25dafd8db37.png)

另一个问题是，新通知样式模式下，可否默认不要展开通知呢？
因为会导致其它通知面板被收拢。（因为媒体播放通知的优先级更高，如果媒体播放通知是默认展开的，其它默认展开的通知就会被收拢，直到关闭aplayer为止其它通知才会被展开。）

当前aplayer新通知样式（默认展开，所以下方tasker通知被Android系统默认收起了）：
![Screenshot_20190425-193910_Chrome](https://user-images.githubusercontent.com/26711804/56733178-fdf32500-6791-11e9-92a3-bc2e8681539a.png)

希望能改成默认不展开（这样tasker或其它展开的通知就不会被系统收起了。）：
![result-2019-04-25-19-48-48](https://user-images.githubusercontent.com/26711804/56733591-334c4280-6793-11e9-955f-85da7c903036.png)

事实上，aplayer新样式的通知展开与否差别只在于桌面歌词开关（锁定）按钮，个人希望可以改成默认不展开，此问题也是我使用经典通知，放弃新通知样式的最大原因，请开发者考虑一下此建议，非常感谢！

**Comment by rRemix** [comment]
如果不展开肯定会有很多人反对的，大部分播放器也都是展开的。这个没办法，只能迎合大众。至于经典通知栏颜色这个问题我尽量适配。暂时你先选择黑色的经典通知栏背景，等我后续修复。

**Comment by Gokou-Ruri** [comment]
请问有没有可能增加一个选项用于控制通知是否展开呢？

**Comment by rRemix** [comment]
这种意义不大的选项尽量少一点，所以暂时先不加了。

**Comment by Gokou-Ruri** [comment]
好的，谢谢回复。

**Comment by rRemix** [comment]
@Gokou-Ruri 新版本通知栏标题能看清了吗？
