### ISSUE TITLE
请求改进歌词匹配算法。

### ISSUE THREAD

**Issue by Gokou-Ruri** [rRemix/APlayer#25]
有大约十几首歌曲的id3信息里，album（专辑）项目都是“花开物语”，可能是因为这个原因，这十几首歌曲差不多有90%都被aplayer匹配到了下面三张图里的这份英文歌词。

![Screenshot_20190415-121658_APlayer](https://user-images.githubusercontent.com/26711804/56734266-ed907980-6794-11e9-9efd-a581db54887c.png)
![Screenshot_20190415-121435_APlayer](https://user-images.githubusercontent.com/26711804/56734289-f97c3b80-6794-11e9-8b48-b2b19c107d12.png)
![Screenshot_20190415-121425_APlayer](https://user-images.githubusercontent.com/26711804/56734292-fda85900-6794-11e9-9574-50772c847f33.png)
![Screenshot_20190415-121412_APlayer](https://user-images.githubusercontent.com/26711804/56734302-01d47680-6795-11e9-9ca9-f6d0f6441d0a.png)
![result-2019-04-25-20-00-05](https://user-images.githubusercontent.com/26711804/56734322-0d27a200-6795-11e9-9eb1-151c083cd0c3.png)
![result-2019-04-25-19-59-46](https://user-images.githubusercontent.com/26711804/56734323-0dc03880-6795-11e9-8474-5fcce255066f.png)
![result-2019-04-25-20-00-27](https://user-images.githubusercontent.com/26711804/56734324-0dc03880-6795-11e9-8a90-bfc2c487eb0f.png)

**Comment by rRemix** [comment]
按理来说标题不一样不应该会匹配到同一歌词的，但也很有可能是bug，或者本身接口返回的就是同一歌词。你先清除一次应用数据，如果还是匹配到同一歌词，你把这几首歌和歌词文件(如果是本地歌词的话)，一起发到568920427@qq.com。

**Comment by Gokou-Ruri** [comment]
已经卸载重装测试过，问题依旧复现，并发送了歌曲和歌词文件给您。

**Comment by rRemix** [comment]
我测试了下，这三首歌歌词相同是因为网易云的接口返回的歌词相同。解决的办法想了想最好就是手动为每首歌设置下歌词。

**Comment by Gokou-Ruri** [comment]
只能用本地歌词吗？

**Comment by Henry-ZHR** [comment]
> 我测试了下，这三首歌歌词相同是因为网易云的接口返回的歌词相同。解决的办法想了想最好就是手动为每首歌设置下歌词。

网易云音乐貌似好多歌词都匹配错了

可以用酷狗的（不过酷狗好像很多没翻译）
