### ISSUE TITLE
歌词问题和封面问题

### ISSUE THREAD

**Issue by laughtLOOL** [rRemix/APlayer#253]
在1.6.3.0版本中,有几个问题,首先是wav格式的音乐不能读取封面,其他信息正常
![image](https://github.com/rRemix/APlayer/assets/83571492/d4425fee-6784-4275-90dd-76b06f526598)

![image](https://github.com/rRemix/APlayer/assets/83571492/88a9dc07-0c35-4a0f-ae35-40b06e3ef1a6)
第二是歌词,在设置中设置了搜索的顺序如下
![image](https://github.com/rRemix/APlayer/assets/83571492/d3b6a364-7994-490b-818f-4a58bea676b6)
但是没用,当搜索不到在线歌词时,不会自动轮循到本地文件上,需要手动选择本地歌词
![image](https://github.com/rRemix/APlayer/assets/83571492/4d0eb47b-e5d2-4ea1-8b6e-3891267f606d)
![image](https://github.com/rRemix/APlayer/assets/83571492/3f210407-8b13-467c-86c1-2847120b5df6)

还有一个问题是歌词显示问题,如果歌词不是utf8或者utf8 BOM编码格式,其他的ANSI格式(在系统自带的笔记本显示编码)或者gbk (GB2312 .Euc-jP,比如...)等会乱码,也就是其他偏门的编码格式不支持,不过在测试了多家软件,例如椒盐,poweramp,lmusic等还有更多都中招,哈哈,其他编码的都不识别,目前我试过的只有海贝音乐支持ansi的编码,不过那个不支持eslyric 0.3,0.5格式的精准歌词,不过我已经把ANSI的批量转成utf8了,这个bug可修可不修

还有就是文件夹哪里能不能新增加一个文件夹跳曲, 还有能不能自定义菜单位置,或者可以隐藏某些不要的功能
还有一个就是希望能把歌词保存的位置保存在其他地方,比如跟歌曲文件同名并在同位置

**Comment by rRemix** [comment]
封面问题应该是三方库的问题，这个有顶改不动，歌词编码同理
搜索不到本地歌词的问题我再找云真机试试，我的手机一直没复现到这个问题
文件夹内跳过和自定义菜单这个目前反馈的人太少了，改动起来性价比不高
歌词保存的问题，主要是跟歌曲同目录的话很有可能在高版本android上没有写入权限

**Comment by laughtLOOL** [comment]
> 封面问题应该是三方库的问题，这个有点改不动，歌词编码同理 搜索不到本地歌词的问题我再找云真机试试，我的手机一直没复现到这个问题 文件夹内跳过和自定义菜单这个目前反馈的人太少了，改动起来性价比不高 歌词保存的问题，主要是跟歌曲同目录的话很有可能在高版本android上没有写入权限

搜索本地歌词我是顺位网易 qq 本地 这样的,如果 网易 qq 在线的这些没有匹配,不会自动选中本地歌词,本地歌词是有的要手动选择,,我的设备是hiby r6一代,  正常的读取写入媒体权限应该够可以了吧

**Comment by rRemix** [comment]
@laughtLOOL 周末我看看这个问题

**Comment by liuzhaoyzz** [comment]
v2.0.2版本已经大幅改进了歌词编码、本地歌词文件搜索等问题，你试试看。
