### ISSUE TITLE
希望支持批量导入m3u，以及导入m3u列表后，歌单列表和m3u定义的顺序保持一致

### ISSUE THREAD

**Issue by wangrongjun** [rRemix/APlayer#254]
我把歌曲和m3u文件都在本地电脑通过git进行管理维护。m3u文件已经做好排序。希望导入后，歌单列表和m3u定义的顺序保持一致

此外，希望能支持一键导入手机某个目录下的全部m3u文件，并且以m3u文件名创建歌单，无需一个个m3u手动导入

**Comment by rRemix** [comment]
排序指的是m3u内歌曲的排序？

**Comment by rRemix** [comment]
目前已经支持多选导入，一键导入这个实现起来有点麻烦

**Comment by wangrongjun** [comment]
多谢！排序是之前没搞清楚，选择自定义就能安装m3u的顺序来排序了。另外，我看只提交了代码到master分支，还没发Release吧，能否发一下？

**Comment by rRemix** [comment]
> 多谢！排序是之前没搞清楚，选择自定义就能安装m3u的顺序来排序了。另外，我看只提交了代码到master分支，还没发Release吧，能否发一下？

预计周末发版
