### ISSUE TITLE
提议：横屏模式下能否将歌词放置左侧或取消专辑图片

### ISSUE THREAD

**Issue by dhr2333** [rRemix/APlayer#257]
主要是在车机上使用，老是忘记歌词想要干净一点看歌词。

**Comment by rRemix** [comment]
这个暂不考虑了

**Comment by dhr2333** [comment]
没打算为车机做适配优化吗？

我试了大概有十几款音乐播放器，要么是无法获取歌词，要么无法从本地听，要么是无法横屏。

这一款已经是车机上最好用的了。

而且目前车机的应用市场，除了视频就是导航，好用的音乐软件确实不好找。

**Comment by rRemix** [comment]
@dhr2333 一般要做更改或者添加新功能需要有一定人数反馈，精力有限

**Comment by dhr2333** [comment]
车主可不会反馈到你这儿来啊。

**Comment by liuzhaoyzz** [comment]
车机上的话，楼主可以开启桌面歌词的功能，并且锁定之。
