### ISSUE TITLE
Aplayer在播放Webdav挂载的音乐时，点击下一首，会出现卡死的情况

### ISSUE THREAD

**Issue by wanrenbuwanxin** [rRemix/APlayer#258]
Aplayer在播放Webdav挂载的音乐时，点击下一首，会出现卡死的情况。网盘里面的歌曲基本为无损，多次点击下一首，大概率卡死。

**Comment by wanrenbuwanxin** [comment]
貌似这个问题是因为缓存太慢的原因？卡死一会之后就可以了。

**Comment by wanrenbuwanxin** [comment]
但是在网盘里面切换的时候速度比较快，用alist挂载的。感觉是webdav-aplayer 中间的速度低

**Comment by wanrenbuwanxin** [comment]
点击下一首必卡死，播放完当前歌曲后也会出现卡死的情况。但是点开播放列表选择下一首就没问题。

**Comment by wanrenbuwanxin** [comment]
最终发现，播放页面点击上一首无问题，点击下一首会出现卡死的情况，播放完当前歌曲更换下一首时会出现卡死的情况，播放裂变随便选择歌曲无问题。

**Comment by rRemix** [comment]
能否提供下测试环境？估计是缓冲比较久，看起像是卡死了 @wanrenbuwanxin

**Comment by wanrenbuwanxin** [comment]
> 能否提供下测试环境？估计是缓冲比较久，看起像是卡死了 @wanrenbuwanxin

webdav链接：http://wscsmile.cn:5244/dav/音乐
账号：admin   密码：123456798

**Comment by rRemix** [comment]
好的，我空了测试下

**Comment by rRemix** [comment]
@wanrenbuwanxin 认证失败，账号或者密码错了？

**Comment by rRemix** [comment]
@wanrenbuwanxin 可以先通过设置里的意见反馈把日志传给我看看，是不是一直在缓冲

**Comment by wanrenbuwanxin** [comment]
> @wanrenbuwanxin 可以先通过设置里的意见反馈把日志传给我， 先看看是不是一直在缓冲

http://wscsmile.cn:5244/dav/音乐
admin      密码：aiyue369714

**Comment by wanrenbuwanxin** [comment]
[Uploading logs.zip…]()

**Comment by wanrenbuwanxin** [comment]
[logs.zip](https://github.com/user-attachments/files/16569120/logs.zip)

**Comment by rRemix** [comment]
@wanrenbuwanxin 复现到了，我尽快修复

**Comment by wanrenbuwanxin** [comment]
> @wanrenbuwanxin 复现到了，我尽快修复

还有个问题就是，webdav获取的歌曲上限只有200首，实际网盘里面比较多

**Comment by wanrenbuwanxin** [comment]
感谢大佬，节假日还在给回复

**Comment by rRemix** [comment]
[APlayer-v1.6.5.0-nonGoogle-withUpdater-release.apk.zip](https://github.com/user-attachments/files/16569986/APlayer-v1.6.5.0-nonGoogle-withUpdater-release.apk.zip)
麻烦试下这个包是否正常

**Comment by wanrenbuwanxin** [comment]
> [APlayer-v1.6.5.0-nonGoogle-withUpdater-release.apk.zip](https://github.com/user-attachments/files/16569986/APlayer-v1.6.5.0-nonGoogle-withUpdater-release.apk.zip) 麻烦试下这个包是否正常

该版本这个问题已经解决，不过有个别的小问题，您看下视频文件

Uploading Screenrecorder-2024-08-11-14-25-37-425.mp4…

**Comment by wanrenbuwanxin** [comment]
https://github.com/user-attachments/assets/06202b7a-05c7-46ac-af5c-e482c6d032dd

该版本这个问题已经解决。不过有个别的小问题，就是每次切换音乐的时候会多做一次封面更替，不知是否是用来解决缓存的。您看下视频文件

**Comment by wanrenbuwanxin** [comment]
> [APlayer-v1.6.5.0-nonGoogle-withUpdater-release.apk.zip](https://github.com/user-attachments/files/16569986/APlayer-v1.6.5.0-nonGoogle-withUpdater-release.apk.zip) 麻烦试下这个包是否正常


https://github.com/user-attachments/assets/20746324-0d54-4671-9e00-bc3474fc7c53
该版本这个问题已经解决。不过有个别的小问题，就是每次切换音乐的时候会多做一次封面更替，不知是否是用来解决缓存的。您看下视频文件

**Comment by rRemix** [comment]
[APlayer-v1.6.5.0-nonGoogle-withUpdater-release.apk.zip](https://github.com/user-attachments/files/16573846/APlayer-v1.6.5.0-nonGoogle-withUpdater-release.apk.zip)

麻烦再试下这个包
1.已经修复，但如果网络不好的情况下界面刷新可能有延迟，这个暂时没办法解决
2.这个就是新需求了，如果还有其他人反馈我再加上

**Comment by wanrenbuwanxin** [comment]
> [APlayer-v1.6.5.0-nonGoogle-withUpdater-release.apk.zip](https://github.com/user-attachments/files/16573846/APlayer-v1.6.5.0-nonGoogle-withUpdater-release.apk.zip)
> 
> @wanrenbuwanxin 麻烦再试下这个包 1.已经修复，但如果网络不好的情况下界面刷新可能有延迟，这个暂时没办法解决 2.这个就是新需求了，如果还有其他人反馈我再加上

感谢大佬，新版本已经完美修复。
