### ISSUE TITLE
桌面歌词锁定之后怎么解锁？

### ISSUE THREAD

**Issue by Yusensee** [rRemix/APlayer#265]
如题，很喜欢你们的软件做得很好。
但我奇怪一个问题就是桌面歌词我按了锁定就是那个锁之后，我怎么才能解锁他呢，他的位置就固定不动了。 我是xiaomiOS，Aplayer版本1.6.4，谢谢。

**Comment by Henry-ZHR** [comment]
通知 有个锁图标 按一下解锁

**Comment by Yusensee** [comment]
😲哦谢谢，找到了
