### ISSUE TITLE
希望可以给歌曲添加自定义标签，用以代替歌曲列表功能，更好管理音乐

### ISSUE THREAD

**Issue by fucaijin** [rRemix/APlayer#266]
不知道你们会不会把歌曲分类，比如“纯音乐”、“老歌”、“温情”、“欢快”、“激情澎湃”、“钢琴曲”等等，直到目前为止我为了实现歌曲分类，是将一个歌曲添加到多个列表中，用列表将歌曲分类，但是很麻烦，因为要把一首歌曲添加到多个不同列表需要多次操作，而且不能同时将多个列表混合随机播放。能不能做个功能，可以新建标签，类似于android的自定义标签列表控件（可以参考：`https://blog.csdn.net/u010177022/article/details/60324117`），然后可以编辑标签，点击勾选出不在此标签内的歌曲，将这些歌曲添加这个标签（也可以理解为将这些歌曲都打上该标签），也可以点击歌曲列表中的歌曲条目，给该歌曲打上1个或多个标签。使用时，用标签来筛选出歌曲，用标签功能完全替代列表的功能。而且随时可以筛选出多个列表中的歌曲，作为当前的播放列表。比如晚上我想听“老歌”、“纯音乐”、“温情”标签的歌曲，我就在筛选标签的弹窗中选中这3个标签，将有这3个标签的歌曲显示并播放（类似于excel中的筛选功能）。感觉这样管理音乐会很方便，目前找了很多APP都没有这个功能

**Comment by rRemix** [comment]
我看了下MediaStore里面支持的数据，并没有tag这种标签，做起来比较麻烦，而且也没有ui设计

**Comment by fucaijin** [comment]
> 我看了下MediaStore里面支持的数据，并没有tag这种标签，做起来比较麻烦，而且也没有ui设计

好的，谢谢你认真研究及答复~等心血来潮时我再看看能不能自己改改
