### ISSUE TITLE
[ A player v1.5.2.1-1521 ] the Equalizer option is not working properly 

### ISSUE THREAD

**Issue by XAMIR555** [rRemix/APlayer#27]
#### Project Information
* Repository    : https://github.com/rRemix/APlayer
* Project Name  : APlayer
* Publisher     :    rRemix

#### Expected behavior
I Expected that  when I click on the Equalizer option should be open all feature  of Equalizer option

#### Actual behavior

during a playing song, when I click on the Equalizer option the Equalizerr option is not working properly
you can see in bug video properly 
 
#### How to reproduce
* [download letest version of application ](https://play.google.com/store/apps/details?id=remix.myplayer)
* open the application 
* play any songs and click on 3 vertical dots 
* click on Equalizer option 
* Note the Bug
* Browser/App version:   v1.5.2.1-1521
* Operating system:  8.0.0 

#### Recording Of The Bug
https://www.youtube.com/watch?v=BzOhRNYmx3I
#### GitHub Account
https://github.com/XAMIR555

**Comment by rRemix** [comment]
@XAMIR555 i'll fix it in the next release.

**Comment by rRemix** [comment]
@XAMIR555 the built-in Equalizer is available now.

**Comment by XAMIR555** [comment]
thanks you sir
