### ISSUE TITLE
[Aplayer][v1.5.2.2]The app can not create new playlist  from songs page.

### ISSUE THREAD

**Issue by maaudrana** [rRemix/APlayer#29]
<h4>Actual  Behaviour </h4>
The app can not create new playlist  from song page.
<h4>Expected Behaviour </h4>
I expected  that i can create new playlist from songs page  and add song to the playlist successfully. 
<h4>Step to reproduce </h4>
<ol>
<li>Download and opens the app</li>
<li>Click songs if you are in other page.</li>
<li>Choose any song and click three horizontal dots</li>
<li>Click add to playlist</li>
<li>Click New playlist</li>
<li>Give playlist name and click create</li>
<li>See the error</li>
</ol>
<h4>Information </h4>
<ul>
<li>App version:v1.5.2.2</li>
<li>Os:Android 9.0</li>
<li>Device:Samsung A10</li>
</ul>
<h4>Recording of the bug</h4>
<a href="https://youtu.be/NsqejXkpMK4">https://youtu.be/NsqejXkpMK4</a>

**Comment by maaudrana** [comment]
@rRemix you there?

**Comment by rRemix** [comment]
@maaudrana thanks for your feedback, i'll fix it as soon as possible

**Comment by rRemix** [comment]
@maaudrana fixed it

**Comment by maaudrana** [comment]
Tnx bro
