### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Blankeer** [rRemix/APlayer#3]
以下大部分是按本地播放器的角度说的.

功能方面:
1. 本地歌词目前是可以手动载入的,建议加入默认加载 mp3 同目录同名 lrc 文件.
2. 歌词解析建议加入 [offset] 标签,见[wiki](https://zh.wikipedia.org/wiki/LRC%E6%A0%BC%E5%BC%8F),这样就可以自己设置标签调节歌词快/慢了.
3. 歌词滚动显示细节优化建议 : 当一句歌词很长时,分行显示间隔太近; 字体大小颜色等貌似无法调节.
4. 桌面歌词建议: 当一句歌词很长时目前是省略最后,体验较好是分行显示 or 滚动显示.
5. 在酷安看到有歌词翻译的功能,貌似没看到说明.

其他:
1. 有些代码格式缩进不规范,如: [LrcRow.java#L40](https://github.com/rRemix/APlayer/blob/master/app/src/main/java/remix/myplayer/lyric/bean/LrcRow.java#L40)
2. 我看到使用了 友盟 微信 微博的 sdk , 仅仅是为了分享操作吗? 感觉有点得不偿失.

谢谢~
祝新年快乐,项目越来越好~

**Comment by rRemix** [comment]
@Blankeer 感谢反馈。歌词这块目前最主要的问题就是大小无法调节，这个近期会修改。还有就是桌面歌词过长的问题。友盟还有就是日常统计吧，崩溃收集那些。
