### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by lyswhut** [rRemix/APlayer#34]
给几个用户体验方面的建议，希望能采纳！

**定时关闭功能建议：**

- 建议可手动输入倒计时时间。
- 新增“播放完当前歌曲再关闭”的开关，即倒计时到了后，是否播放完当前歌曲再关闭，这样不会显得突兀。

**通知栏建议：**

- 建议在通知栏右上角新增关闭按钮，点击即可快速退出播放器。当想要关闭播放器时，只要下拉通知栏点关闭按钮即可快速关闭，不需要点进播放器关闭。

**Comment by rRemix** [comment]
1.手动输入这个先不做了，没人设计ui；播放完再关闭这个下版本添加，默认就开启。
2.这个你其实暂停后把通知栏划掉也算是关闭了。

**Comment by zlhdd108** [comment]
建议可以增加几个常用的均衡器，之前用“轻听”的时候有几个内置的均衡器，还比较好用
