### ISSUE TITLE
超过 10MB 的项目请另传一份在码云，谢谢

### ISSUE THREAD

**Issue by KunMinX** [rRemix/APlayer#38]
我上次下载过一个 280MB 的项目，真的是开眼界了，项目本身没什么，却足足下了一天（100MB网速，10KB下载速度你懂得，期间一直失败）

**Comment by rRemix** [comment]
@KunMinX 加个--depth 1拉取最近一次提交就行了。以前不太会用git，上传了很多无用的build文件，导致历史记录特别大。

**Comment by KunMinX** [comment]
@rRemix  好的，感谢你的建议！
