### ISSUE TITLE
功能建议：希望能在近期更新中添加耳机线控的功能

### ISSUE THREAD

**Issue by PianCat** [rRemix/APlayer#46]
APlayer是我用过的最好用的本地播放器，但是有一个功能的缺席令我有些难受

在此诚挚的建议开发者添加耳机线控功能进APlayer，不用太复杂的，Phonograph那种就好

如愿意添加，不尽感谢

**Comment by rRemix** [comment]
线控很早就有了。

**Comment by chipyongni** [comment]
的确已有线控播放/暂停、增加/减少音量，如果在加上双击/三击切换上/下一首的功能就完美啦
