### ISSUE TITLE
APlayer won't start playing the file when being started by system intents.

### ISSUE THREAD

**Issue by cyanlink** [rRemix/APlayer#48]
~~1. Open any file explorer, open any music file.
2. In the App Chooser pop-up, choose APlayer
3. APlayer main activity starts, but the chosen file won't start playing.
Reason: a intent filter with action "android.intent.action.VIEW" is specified in AndroidManifest under MainActivity, but the corresponding file handling logic is not implemented.~~

Ok, so the real problem is:
(Under MIUI 10)
1. Kill APlayer (Remove from activity list)
2. Go to ZArchiver, open some random music file with APlayer.
3. APlayer MainActivity starts, but remains the last song before the kill (will be paused), new file will not be played (As if the parseIntent() function in onCreate() is not fired).
And:
4. If APlayer is still alive in background (started from launcher/started by other apps' intents).
5. Aplayer can start playing any requested music file.
Maybe this is a MIUI "feature".

**Comment by cyanlink** [comment]
edit: there is no .nomedia effecting the music files. Even though there is a .nomedia, the app should still play the music.

**Comment by rRemix** [comment]
The most likely reason is your file explorer pass me a wrong path,causing app faile to parse file.
You can change a file explorer and retry. @cyanlink

**Comment by cyanlink** [comment]
@rRemix The initial reproduce procedure is not correct. I'm using ZArchiver, and the problem can be reproduced. Still trying it out to nail down the problem.

**Comment by cyanlink** [comment]
Ok, so the real problem is:
(Under MIUI 10)
1. Kill APlayer (Remove from activity list)
2. Go to ZArchiver, open some random music file with APlayer.
3. APlayer MainActivity starts, but remains the last song before the kill (will be paused), new file will not be played (As if the parseIntent() function in onCreate() is not fired).
And:
1: If APlayer is still alive in background (started from launcher/started by other apps' intents).
2. Aplayer can start playing any requested music file.
Maybe this is a MIUI "feature".

**Comment by rRemix** [comment]
it seems that the problem is exist,i'll fix it in next release @cyanlink

**Comment by cyanlink** [comment]
@rRemix but what could be the possible cause? is this related to activity lifecycle (and you should parse intent in onStart() or something?)

**Comment by rRemix** [comment]
you are right, please see changes in the MainActivity. [https://github.com/rRemix/APlayer/commit/c6f4934eb3893bea7c865220131cc32758e616ae#diff-f6da2fcc52e88edcbec3d15d409496e0](url)
@cyanlink
