### ISSUE TITLE
停止播放后再次打开会无法播放

### ISSUE THREAD

**Issue by Blankeer** [rRemix/APlayer#6]
发现过几次.
停止播放后不杀死进程,挂在后台,等一段时间后打开,点击任何音乐都是播放不了的,像是"播放假死",此时杀死进程,重启,就正常了.

**Comment by rRemix** [comment]
尝试修复了下。看新版本用户反馈了。

**Comment by shimonoaria** [comment]
MediaPlayer{what:-10000,extra:0} is being reinitialized
