### ISSUE TITLE
在播放特定文件时反复初始化

### ISSUE THREAD

**Issue by Lannamokia** [rRemix/APlayer#67]
在播放从qq音乐上下载的一个FLAC文件时反复初始化

**Comment by Henry-ZHR** [comment]
其他播放器能播放吗？

文件发一下？

**Comment by Lannamokia** [comment]
[文件链接](https://pan.baidu.com/s/1CNhF2_sjY1cGiF9RMTiE8g p7dm) 
就这样的一个文件，其他播放器都行

**Comment by Lannamokia** [comment]
> [文件链接](https://pan.baidu.com/s/1CNhF2_sjY1cGiF9RMTiE8g) 提取码:p7dm
> 就这样的一个文件，其他播放器都行

**Comment by Lannamokia** [comment]
第一个提取码发错了

**Comment by Lannamokia** [comment]
其他带解码器的播放器和原生系统自带音乐都行

**Comment by Henry-ZHR** [comment]
本地没问题，可以正常播放

**Comment by Henry-ZHR** [comment]
应用版本多少？

**Comment by Lannamokia** [comment]
![Screenshot_20200621-224951](https://user-images.githubusercontent.com/67230455/85227695-92e2c400-b411-11ea-8c2a-d1d7d3ed7cd9.png)

**Comment by Lannamokia** [comment]
会不会是机子的问题，有挺多软件在多亲2上发癫

**Comment by rRemix** [comment]
这种基本跟你的rom关系比较大

**Comment by Henry-ZHR** [comment]
> 在播放从qq音乐上下载的一个FLAC文件时反复初始化
> 
> 

对了，顺便问下，QQ音乐能下无损音质？
